// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AplicacionDbContext))]
    [Migration("20260831214127_QuitarIdDePrecio")]
    partial class QuitarIdDePrecio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Modelo.Dominio.Cancha", b =>
                {
                    b.Property<int>("ComplejoId")
                        .HasColumnType("int");

                    b.Property<int>("Nro")
                        .HasColumnType("int");

                    b.Property<int>("TipoCanchaId")
                        .HasColumnType("int");

                    b.HasKey("ComplejoId", "Nro");

                    b.HasIndex("TipoCanchaId");

                    b.ToTable("Canchas");
                });

            modelBuilder.Entity("Modelo.Dominio.Complejo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DueñoId")
                        .HasColumnType("int");

                    b.Property<int>("EncargadoId")
                        .HasColumnType("int");

                    b.Property<int>("LocalidadId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DueñoId");

                    b.HasIndex("EncargadoId")
                        .IsUnique();

                    b.HasIndex("LocalidadId");

                    b.ToTable("Complejos");
                });

            modelBuilder.Entity("Modelo.Dominio.Horario", b =>
                {
                    b.Property<int>("ComplejoId")
                        .HasColumnType("int");

                    b.Property<int>("NroDia")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("HoraApertura")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraCierre")
                        .HasColumnType("time");

                    b.HasKey("ComplejoId", "NroDia");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("Modelo.Dominio.Localidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Localidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoPostal = "B1900",
                            Nombre = "La Plata",
                            ProvinciaId = 1
                        },
                        new
                        {
                            Id = 2,
                            CodigoPostal = "B7600",
                            Nombre = "Mar del Plata",
                            ProvinciaId = 1
                        },
                        new
                        {
                            Id = 3,
                            CodigoPostal = "B8000",
                            Nombre = "Bahía Blanca",
                            ProvinciaId = 1
                        },
                        new
                        {
                            Id = 4,
                            CodigoPostal = "B7000",
                            Nombre = "Tandil",
                            ProvinciaId = 1
                        },
                        new
                        {
                            Id = 5,
                            CodigoPostal = "B2900",
                            Nombre = "San Nicolás de los Arroyos",
                            ProvinciaId = 1
                        },
                        new
                        {
                            Id = 6,
                            CodigoPostal = "C1425",
                            Nombre = "Palermo",
                            ProvinciaId = 2
                        },
                        new
                        {
                            Id = 7,
                            CodigoPostal = "C1428",
                            Nombre = "Belgrano",
                            ProvinciaId = 2
                        },
                        new
                        {
                            Id = 8,
                            CodigoPostal = "C1405",
                            Nombre = "Caballito",
                            ProvinciaId = 2
                        },
                        new
                        {
                            Id = 9,
                            CodigoPostal = "C1063",
                            Nombre = "San Telmo",
                            ProvinciaId = 2
                        },
                        new
                        {
                            Id = 10,
                            CodigoPostal = "C1113",
                            Nombre = "Recoleta",
                            ProvinciaId = 2
                        },
                        new
                        {
                            Id = 11,
                            CodigoPostal = "K4700",
                            Nombre = "San Fernando del Valle de Catamarca",
                            ProvinciaId = 3
                        },
                        new
                        {
                            Id = 12,
                            CodigoPostal = "K4750",
                            Nombre = "Belén",
                            ProvinciaId = 3
                        },
                        new
                        {
                            Id = 13,
                            CodigoPostal = "K4740",
                            Nombre = "Andalgalá",
                            ProvinciaId = 3
                        },
                        new
                        {
                            Id = 14,
                            CodigoPostal = "K5340",
                            Nombre = "Tinogasta",
                            ProvinciaId = 3
                        },
                        new
                        {
                            Id = 15,
                            CodigoPostal = "K4139",
                            Nombre = "Santa María",
                            ProvinciaId = 3
                        },
                        new
                        {
                            Id = 16,
                            CodigoPostal = "H3500",
                            Nombre = "Resistencia",
                            ProvinciaId = 4
                        },
                        new
                        {
                            Id = 17,
                            CodigoPostal = "H3700",
                            Nombre = "Presidencia Roque Sáenz Peña",
                            ProvinciaId = 4
                        },
                        new
                        {
                            Id = 18,
                            CodigoPostal = "H3540",
                            Nombre = "Villa Ángela",
                            ProvinciaId = 4
                        },
                        new
                        {
                            Id = 19,
                            CodigoPostal = "H3732",
                            Nombre = "General Pinedo",
                            ProvinciaId = 4
                        },
                        new
                        {
                            Id = 20,
                            CodigoPostal = "H3730",
                            Nombre = "Charata",
                            ProvinciaId = 4
                        },
                        new
                        {
                            Id = 21,
                            CodigoPostal = "U9103",
                            Nombre = "Rawson",
                            ProvinciaId = 5
                        },
                        new
                        {
                            Id = 22,
                            CodigoPostal = "U9120",
                            Nombre = "Puerto Madryn",
                            ProvinciaId = 5
                        },
                        new
                        {
                            Id = 23,
                            CodigoPostal = "U9100",
                            Nombre = "Trelew",
                            ProvinciaId = 5
                        },
                        new
                        {
                            Id = 24,
                            CodigoPostal = "U9000",
                            Nombre = "Comodoro Rivadavia",
                            ProvinciaId = 5
                        },
                        new
                        {
                            Id = 25,
                            CodigoPostal = "U9200",
                            Nombre = "Esquel",
                            ProvinciaId = 5
                        },
                        new
                        {
                            Id = 26,
                            CodigoPostal = "X5000",
                            Nombre = "Córdoba Capital",
                            ProvinciaId = 6
                        },
                        new
                        {
                            Id = 27,
                            CodigoPostal = "X5152",
                            Nombre = "Villa Carlos Paz",
                            ProvinciaId = 6
                        },
                        new
                        {
                            Id = 28,
                            CodigoPostal = "X5800",
                            Nombre = "Río Cuarto",
                            ProvinciaId = 6
                        },
                        new
                        {
                            Id = 29,
                            CodigoPostal = "X5900",
                            Nombre = "Villa María",
                            ProvinciaId = 6
                        },
                        new
                        {
                            Id = 30,
                            CodigoPostal = "X2400",
                            Nombre = "San Francisco",
                            ProvinciaId = 6
                        },
                        new
                        {
                            Id = 31,
                            CodigoPostal = "W3400",
                            Nombre = "Corrientes Capital",
                            ProvinciaId = 7
                        },
                        new
                        {
                            Id = 32,
                            CodigoPostal = "W3450",
                            Nombre = "Goya",
                            ProvinciaId = 7
                        },
                        new
                        {
                            Id = 33,
                            CodigoPostal = "W3230",
                            Nombre = "Paso de los Libres",
                            ProvinciaId = 7
                        },
                        new
                        {
                            Id = 34,
                            CodigoPostal = "W3460",
                            Nombre = "Curuzú Cuatiá",
                            ProvinciaId = 7
                        },
                        new
                        {
                            Id = 35,
                            CodigoPostal = "W3470",
                            Nombre = "Mercedes",
                            ProvinciaId = 7
                        },
                        new
                        {
                            Id = 36,
                            CodigoPostal = "E3100",
                            Nombre = "Paraná",
                            ProvinciaId = 8
                        },
                        new
                        {
                            Id = 37,
                            CodigoPostal = "E3200",
                            Nombre = "Concordia",
                            ProvinciaId = 8
                        },
                        new
                        {
                            Id = 38,
                            CodigoPostal = "E2820",
                            Nombre = "Gualeguaychú",
                            ProvinciaId = 8
                        },
                        new
                        {
                            Id = 39,
                            CodigoPostal = "E3260",
                            Nombre = "Concepción del Uruguay",
                            ProvinciaId = 8
                        },
                        new
                        {
                            Id = 40,
                            CodigoPostal = "E3153",
                            Nombre = "Victoria",
                            ProvinciaId = 8
                        },
                        new
                        {
                            Id = 41,
                            CodigoPostal = "P3600",
                            Nombre = "Formosa Capital",
                            ProvinciaId = 9
                        },
                        new
                        {
                            Id = 42,
                            CodigoPostal = "P3610",
                            Nombre = "Clorinda",
                            ProvinciaId = 9
                        },
                        new
                        {
                            Id = 43,
                            CodigoPostal = "P3606",
                            Nombre = "Pirané",
                            ProvinciaId = 9
                        },
                        new
                        {
                            Id = 44,
                            CodigoPostal = "P3603",
                            Nombre = "El Colorado",
                            ProvinciaId = 9
                        },
                        new
                        {
                            Id = 45,
                            CodigoPostal = "P3630",
                            Nombre = "Las Lomitas",
                            ProvinciaId = 9
                        },
                        new
                        {
                            Id = 46,
                            CodigoPostal = "Y4600",
                            Nombre = "San Salvador de Jujuy",
                            ProvinciaId = 10
                        },
                        new
                        {
                            Id = 47,
                            CodigoPostal = "Y4500",
                            Nombre = "San Pedro de Jujuy",
                            ProvinciaId = 10
                        },
                        new
                        {
                            Id = 48,
                            CodigoPostal = "Y4624",
                            Nombre = "Tilcara",
                            ProvinciaId = 10
                        },
                        new
                        {
                            Id = 49,
                            CodigoPostal = "Y4630",
                            Nombre = "Humahuaca",
                            ProvinciaId = 10
                        },
                        new
                        {
                            Id = 50,
                            CodigoPostal = "Y4650",
                            Nombre = "La Quiaca",
                            ProvinciaId = 10
                        },
                        new
                        {
                            Id = 51,
                            CodigoPostal = "L6300",
                            Nombre = "Santa Rosa",
                            ProvinciaId = 11
                        },
                        new
                        {
                            Id = 52,
                            CodigoPostal = "L6360",
                            Nombre = "General Pico",
                            ProvinciaId = 11
                        },
                        new
                        {
                            Id = 53,
                            CodigoPostal = "L6303",
                            Nombre = "Toay",
                            ProvinciaId = 11
                        },
                        new
                        {
                            Id = 54,
                            CodigoPostal = "L6200",
                            Nombre = "Realicó",
                            ProvinciaId = 11
                        },
                        new
                        {
                            Id = 55,
                            CodigoPostal = "L8200",
                            Nombre = "General Acha",
                            ProvinciaId = 11
                        },
                        new
                        {
                            Id = 56,
                            CodigoPostal = "F5300",
                            Nombre = "La Rioja Capital",
                            ProvinciaId = 12
                        },
                        new
                        {
                            Id = 57,
                            CodigoPostal = "F5360",
                            Nombre = "Chilecito",
                            ProvinciaId = 12
                        },
                        new
                        {
                            Id = 58,
                            CodigoPostal = "F5310",
                            Nombre = "Aimogasta",
                            ProvinciaId = 12
                        },
                        new
                        {
                            Id = 59,
                            CodigoPostal = "F5380",
                            Nombre = "Chamical",
                            ProvinciaId = 12
                        },
                        new
                        {
                            Id = 60,
                            CodigoPostal = "F5350",
                            Nombre = "Villa Unión",
                            ProvinciaId = 12
                        },
                        new
                        {
                            Id = 61,
                            CodigoPostal = "M5500",
                            Nombre = "Mendoza Capital",
                            ProvinciaId = 13
                        },
                        new
                        {
                            Id = 62,
                            CodigoPostal = "M5600",
                            Nombre = "San Rafael",
                            ProvinciaId = 13
                        },
                        new
                        {
                            Id = 63,
                            CodigoPostal = "M5501",
                            Nombre = "Godoy Cruz",
                            ProvinciaId = 13
                        },
                        new
                        {
                            Id = 64,
                            CodigoPostal = "M5515",
                            Nombre = "Maipú",
                            ProvinciaId = 13
                        },
                        new
                        {
                            Id = 65,
                            CodigoPostal = "M5613",
                            Nombre = "Malargüe",
                            ProvinciaId = 13
                        },
                        new
                        {
                            Id = 66,
                            CodigoPostal = "N3300",
                            Nombre = "Posadas",
                            ProvinciaId = 14
                        },
                        new
                        {
                            Id = 67,
                            CodigoPostal = "N3370",
                            Nombre = "Puerto Iguazú",
                            ProvinciaId = 14
                        },
                        new
                        {
                            Id = 68,
                            CodigoPostal = "N3360",
                            Nombre = "Oberá",
                            ProvinciaId = 14
                        },
                        new
                        {
                            Id = 69,
                            CodigoPostal = "N3380",
                            Nombre = "Eldorado",
                            ProvinciaId = 14
                        },
                        new
                        {
                            Id = 70,
                            CodigoPostal = "N3350",
                            Nombre = "Apostoles",
                            ProvinciaId = 14
                        },
                        new
                        {
                            Id = 71,
                            CodigoPostal = "Q8300",
                            Nombre = "Neuquén Capital",
                            ProvinciaId = 15
                        },
                        new
                        {
                            Id = 72,
                            CodigoPostal = "Q8370",
                            Nombre = "San Martín de los Andes",
                            ProvinciaId = 15
                        },
                        new
                        {
                            Id = 73,
                            CodigoPostal = "Q8407",
                            Nombre = "Villa La Angostura",
                            ProvinciaId = 15
                        },
                        new
                        {
                            Id = 74,
                            CodigoPostal = "Q8340",
                            Nombre = "Zapala",
                            ProvinciaId = 15
                        },
                        new
                        {
                            Id = 75,
                            CodigoPostal = "Q8322",
                            Nombre = "Cutral Có",
                            ProvinciaId = 15
                        },
                        new
                        {
                            Id = 76,
                            CodigoPostal = "R8500",
                            Nombre = "Viedma",
                            ProvinciaId = 16
                        },
                        new
                        {
                            Id = 77,
                            CodigoPostal = "R8400",
                            Nombre = "San Carlos de Bariloche",
                            ProvinciaId = 16
                        },
                        new
                        {
                            Id = 78,
                            CodigoPostal = "R8332",
                            Nombre = "General Roca",
                            ProvinciaId = 16
                        },
                        new
                        {
                            Id = 79,
                            CodigoPostal = "R8324",
                            Nombre = "Cipolletti",
                            ProvinciaId = 16
                        },
                        new
                        {
                            Id = 80,
                            CodigoPostal = "R8521",
                            Nombre = "Las Grutas",
                            ProvinciaId = 16
                        },
                        new
                        {
                            Id = 81,
                            CodigoPostal = "A4400",
                            Nombre = "Salta Capital",
                            ProvinciaId = 17
                        },
                        new
                        {
                            Id = 82,
                            CodigoPostal = "A4427",
                            Nombre = "Cafayate",
                            ProvinciaId = 17
                        },
                        new
                        {
                            Id = 83,
                            CodigoPostal = "A4530",
                            Nombre = "San Ramón de la Nueva Orán",
                            ProvinciaId = 17
                        },
                        new
                        {
                            Id = 84,
                            CodigoPostal = "A4560",
                            Nombre = "Tartagal",
                            ProvinciaId = 17
                        },
                        new
                        {
                            Id = 85,
                            CodigoPostal = "A4432",
                            Nombre = "General Güemes",
                            ProvinciaId = 17
                        },
                        new
                        {
                            Id = 86,
                            CodigoPostal = "J5400",
                            Nombre = "San Juan Capital",
                            ProvinciaId = 18
                        },
                        new
                        {
                            Id = 87,
                            CodigoPostal = "J5425",
                            Nombre = "Rawson",
                            ProvinciaId = 18
                        },
                        new
                        {
                            Id = 88,
                            CodigoPostal = "J5413",
                            Nombre = "Chimbas",
                            ProvinciaId = 18
                        },
                        new
                        {
                            Id = 89,
                            CodigoPostal = "J5442",
                            Nombre = "Caucete",
                            ProvinciaId = 18
                        },
                        new
                        {
                            Id = 90,
                            CodigoPostal = "J5460",
                            Nombre = "Jáchal",
                            ProvinciaId = 18
                        },
                        new
                        {
                            Id = 91,
                            CodigoPostal = "D5700",
                            Nombre = "San Luis Capital",
                            ProvinciaId = 19
                        },
                        new
                        {
                            Id = 92,
                            CodigoPostal = "D5730",
                            Nombre = "Villa Mercedes",
                            ProvinciaId = 19
                        },
                        new
                        {
                            Id = 93,
                            CodigoPostal = "D5881",
                            Nombre = "Merlo",
                            ProvinciaId = 19
                        },
                        new
                        {
                            Id = 94,
                            CodigoPostal = "D5703",
                            Nombre = "La Punta",
                            ProvinciaId = 19
                        },
                        new
                        {
                            Id = 95,
                            CodigoPostal = "D5738",
                            Nombre = "Justo Daract",
                            ProvinciaId = 19
                        },
                        new
                        {
                            Id = 96,
                            CodigoPostal = "Z9400",
                            Nombre = "Río Gallegos",
                            ProvinciaId = 20
                        },
                        new
                        {
                            Id = 97,
                            CodigoPostal = "Z9405",
                            Nombre = "El Calafate",
                            ProvinciaId = 20
                        },
                        new
                        {
                            Id = 98,
                            CodigoPostal = "Z9011",
                            Nombre = "Caleta Olivia",
                            ProvinciaId = 20
                        },
                        new
                        {
                            Id = 99,
                            CodigoPostal = "Z9050",
                            Nombre = "Puerto Deseado",
                            ProvinciaId = 20
                        },
                        new
                        {
                            Id = 100,
                            CodigoPostal = "Z9301",
                            Nombre = "El Chaltén",
                            ProvinciaId = 20
                        },
                        new
                        {
                            Id = 101,
                            CodigoPostal = "S3000",
                            Nombre = "Santa Fe Capital",
                            ProvinciaId = 21
                        },
                        new
                        {
                            Id = 102,
                            CodigoPostal = "S2000",
                            Nombre = "Rosario",
                            ProvinciaId = 21
                        },
                        new
                        {
                            Id = 103,
                            CodigoPostal = "S2300",
                            Nombre = "Rafaela",
                            ProvinciaId = 21
                        },
                        new
                        {
                            Id = 104,
                            CodigoPostal = "S2600",
                            Nombre = "Venado Tuerto",
                            ProvinciaId = 21
                        },
                        new
                        {
                            Id = 105,
                            CodigoPostal = "S3500",
                            Nombre = "Reconquista",
                            ProvinciaId = 21
                        },
                        new
                        {
                            Id = 106,
                            CodigoPostal = "G4200",
                            Nombre = "Santiago del Estero Capital",
                            ProvinciaId = 22
                        },
                        new
                        {
                            Id = 107,
                            CodigoPostal = "G4200",
                            Nombre = "La Banda",
                            ProvinciaId = 22
                        },
                        new
                        {
                            Id = 108,
                            CodigoPostal = "G4220",
                            Nombre = "Termas de Río Hondo",
                            ProvinciaId = 22
                        },
                        new
                        {
                            Id = 109,
                            CodigoPostal = "G3760",
                            Nombre = "Añatuya",
                            ProvinciaId = 22
                        },
                        new
                        {
                            Id = 110,
                            CodigoPostal = "G4230",
                            Nombre = "Frías",
                            ProvinciaId = 22
                        },
                        new
                        {
                            Id = 111,
                            CodigoPostal = "V9410",
                            Nombre = "Ushuaia",
                            ProvinciaId = 23
                        },
                        new
                        {
                            Id = 112,
                            CodigoPostal = "V9420",
                            Nombre = "Río Grande",
                            ProvinciaId = 23
                        },
                        new
                        {
                            Id = 113,
                            CodigoPostal = "V9412",
                            Nombre = "Tolhuin",
                            ProvinciaId = 23
                        },
                        new
                        {
                            Id = 114,
                            CodigoPostal = "V9410",
                            Nombre = "Puerto Almanza",
                            ProvinciaId = 23
                        },
                        new
                        {
                            Id = 115,
                            CodigoPostal = "V9420",
                            Nombre = "San Sebastián",
                            ProvinciaId = 23
                        },
                        new
                        {
                            Id = 116,
                            CodigoPostal = "T4000",
                            Nombre = "San Miguel de Tucumán",
                            ProvinciaId = 24
                        },
                        new
                        {
                            Id = 117,
                            CodigoPostal = "T4107",
                            Nombre = "Yerba Buena",
                            ProvinciaId = 24
                        },
                        new
                        {
                            Id = 118,
                            CodigoPostal = "T4137",
                            Nombre = "Tafí del Valle",
                            ProvinciaId = 24
                        },
                        new
                        {
                            Id = 119,
                            CodigoPostal = "T4147",
                            Nombre = "Concepción",
                            ProvinciaId = 24
                        },
                        new
                        {
                            Id = 120,
                            CodigoPostal = "T4109",
                            Nombre = "Banda del Río Salí",
                            ProvinciaId = 24
                        });
                });

            modelBuilder.Entity("Modelo.Dominio.PersonaFisica", b =>
                {
                    b.Property<string>("Dni")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Dni");

                    b.ToTable("PersonaFisicas");
                });

            modelBuilder.Entity("Modelo.Dominio.PersonaJuridica", b =>
                {
                    b.Property<string>("Cuit")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cuit");

                    b.ToTable("PersonaJuridicas");
                });

            modelBuilder.Entity("Modelo.Dominio.Precio", b =>
                {
                    b.Property<int>("ComplejoId")
                        .HasColumnType("int");

                    b.Property<int>("CanchaNro")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaDesde")
                        .HasColumnType("date");

                    b.Property<decimal>("PrecioAdicional")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioSena")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ComplejoId", "CanchaNro", "FechaDesde");

                    b.ToTable("Precios");
                });

            modelBuilder.Entity("Modelo.Dominio.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provincias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Buenos Aires"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Ciudad Autónoma de Buenos Aires"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Catamarca"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Chaco"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Chubut"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Córdoba"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Corrientes"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Entre Ríos"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Formosa"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Jujuy"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "La Pampa"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "La Rioja"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Mendoza"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Misiones"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Neuquén"
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Río Negro"
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "Salta"
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "San Juan"
                        },
                        new
                        {
                            Id = 19,
                            Nombre = "San Luis"
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Santa Cruz"
                        },
                        new
                        {
                            Id = 21,
                            Nombre = "Santa Fe"
                        },
                        new
                        {
                            Id = 22,
                            Nombre = "Santiago del Estero"
                        },
                        new
                        {
                            Id = 23,
                            Nombre = "Tierra del Fuego, Antártida e Islas del Atlántico Sur"
                        },
                        new
                        {
                            Id = 24,
                            Nombre = "Tucumán"
                        });
                });

            modelBuilder.Entity("Modelo.Dominio.TipoCancha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Deporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoCanchas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deporte = "Futbol 11"
                        },
                        new
                        {
                            Id = 2,
                            Deporte = "Futbol 5"
                        },
                        new
                        {
                            Id = 3,
                            Deporte = "Futbol 7"
                        },
                        new
                        {
                            Id = 4,
                            Deporte = "Futsal"
                        },
                        new
                        {
                            Id = 5,
                            Deporte = "Padel"
                        },
                        new
                        {
                            Id = 6,
                            Deporte = "Tenis"
                        },
                        new
                        {
                            Id = 7,
                            Deporte = "Ping Pong"
                        },
                        new
                        {
                            Id = 8,
                            Deporte = "Hockey"
                        },
                        new
                        {
                            Id = 9,
                            Deporte = "Basket"
                        },
                        new
                        {
                            Id = 10,
                            Deporte = "Voley"
                        });
                });

            modelBuilder.Entity("Modelo.Dominio.TipoTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoTurnos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Turno basico",
                            Nombre = "Normal"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Turno reservado periodicamente",
                            Nombre = "Fijo"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Turno reservado para un evento en particular",
                            Nombre = "Evento"
                        });
                });

            modelBuilder.Entity("Modelo.Dominio.TipoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoUsuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Encargado"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Cliente"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Dueño"
                        });
                });

            modelBuilder.Entity("Modelo.Dominio.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CanchaNro")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("ComplejoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<string>("MotivoCancelacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoTurnoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TipoTurnoId");

                    b.HasIndex("ComplejoId", "CanchaNro");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("Modelo.Dominio.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonaFisicaDni")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PersonaJuridicaCuit")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaFisicaDni");

                    b.HasIndex("PersonaJuridicaCuit");

                    b.HasIndex("TipoUsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Modelo.Dominio.Cancha", b =>
                {
                    b.HasOne("Modelo.Dominio.Complejo", "Complejo")
                        .WithMany("Canchas")
                        .HasForeignKey("ComplejoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo.Dominio.TipoCancha", "TipoCancha")
                        .WithMany("Canchas")
                        .HasForeignKey("TipoCanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complejo");

                    b.Navigation("TipoCancha");
                });

            modelBuilder.Entity("Modelo.Dominio.Complejo", b =>
                {
                    b.HasOne("Modelo.Dominio.Usuario", "Dueño")
                        .WithMany("Complejos")
                        .HasForeignKey("DueñoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelo.Dominio.Usuario", "Encargado")
                        .WithOne("Complejo")
                        .HasForeignKey("Modelo.Dominio.Complejo", "EncargadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelo.Dominio.Localidad", "Localidad")
                        .WithMany("Complejos")
                        .HasForeignKey("LocalidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dueño");

                    b.Navigation("Encargado");

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("Modelo.Dominio.Horario", b =>
                {
                    b.HasOne("Modelo.Dominio.Complejo", "Complejo")
                        .WithMany("Horarios")
                        .HasForeignKey("ComplejoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complejo");
                });

            modelBuilder.Entity("Modelo.Dominio.Localidad", b =>
                {
                    b.HasOne("Modelo.Dominio.Provincia", "Provincia")
                        .WithMany("Localidades")
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("Modelo.Dominio.Precio", b =>
                {
                    b.HasOne("Modelo.Dominio.Cancha", "Cancha")
                        .WithMany("Precios")
                        .HasForeignKey("ComplejoId", "CanchaNro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");
                });

            modelBuilder.Entity("Modelo.Dominio.Turno", b =>
                {
                    b.HasOne("Modelo.Dominio.Usuario", "Cliente")
                        .WithMany("Turnos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelo.Dominio.Complejo", "Complejo")
                        .WithMany()
                        .HasForeignKey("ComplejoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo.Dominio.TipoTurno", "TipoTurno")
                        .WithMany("Turnos")
                        .HasForeignKey("TipoTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelo.Dominio.Cancha", "Cancha")
                        .WithMany("Turnos")
                        .HasForeignKey("ComplejoId", "CanchaNro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Cliente");

                    b.Navigation("Complejo");

                    b.Navigation("TipoTurno");
                });

            modelBuilder.Entity("Modelo.Dominio.Usuario", b =>
                {
                    b.HasOne("Modelo.Dominio.PersonaFisica", "PersonaFisica")
                        .WithMany("Usuarios")
                        .HasForeignKey("PersonaFisicaDni");

                    b.HasOne("Modelo.Dominio.PersonaJuridica", "PersonaJuridica")
                        .WithMany("Usuarios")
                        .HasForeignKey("PersonaJuridicaCuit");

                    b.HasOne("Modelo.Dominio.TipoUsuario", "TipoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonaFisica");

                    b.Navigation("PersonaJuridica");

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("Modelo.Dominio.Cancha", b =>
                {
                    b.Navigation("Precios");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Modelo.Dominio.Complejo", b =>
                {
                    b.Navigation("Canchas");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("Modelo.Dominio.Localidad", b =>
                {
                    b.Navigation("Complejos");
                });

            modelBuilder.Entity("Modelo.Dominio.PersonaFisica", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Modelo.Dominio.PersonaJuridica", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Modelo.Dominio.Provincia", b =>
                {
                    b.Navigation("Localidades");
                });

            modelBuilder.Entity("Modelo.Dominio.TipoCancha", b =>
                {
                    b.Navigation("Canchas");
                });

            modelBuilder.Entity("Modelo.Dominio.TipoTurno", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Modelo.Dominio.TipoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Modelo.Dominio.Usuario", b =>
                {
                    b.Navigation("Complejo")
                        .IsRequired();

                    b.Navigation("Complejos");

                    b.Navigation("Turnos");
                });
#pragma warning restore 612, 618
        }
    }
}
