// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AplicacionDbContext))]
    [Migration("20260831154718_SeedTipoCanchaTurno")]
    partial class SeedTipoCanchaTurno
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Modelo.Dominio.Cancha", b =>
                {
                    b.Property<int>("ComplejoId")
                        .HasColumnType("int");

                    b.Property<int>("Nro")
                        .HasColumnType("int");

                    b.Property<int>("TipoCanchaId")
                        .HasColumnType("int");

                    b.HasKey("ComplejoId", "Nro");

                    b.HasIndex("TipoCanchaId");

                    b.ToTable("Canchas");
                });

            modelBuilder.Entity("Modelo.Dominio.Complejo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DueñoId")
                        .HasColumnType("int");

                    b.Property<int>("EncargadoId")
                        .HasColumnType("int");

                    b.Property<int>("LocalidadId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DueñoId");

                    b.HasIndex("EncargadoId")
                        .IsUnique();

                    b.HasIndex("LocalidadId");

                    b.ToTable("Complejos");
                });

            modelBuilder.Entity("Modelo.Dominio.Horario", b =>
                {
                    b.Property<int>("ComplejoId")
                        .HasColumnType("int");

                    b.Property<int>("NroDia")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("HoraApertura")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraCierre")
                        .HasColumnType("time");

                    b.HasKey("ComplejoId", "NroDia");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("Modelo.Dominio.Localidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Localidades");
                });

            modelBuilder.Entity("Modelo.Dominio.PersonaFisica", b =>
                {
                    b.Property<string>("Dni")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Dni");

                    b.ToTable("PersonaFisicas");
                });

            modelBuilder.Entity("Modelo.Dominio.PersonaJuridica", b =>
                {
                    b.Property<string>("Cuit")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cuit");

                    b.ToTable("PersonaJuridicas");
                });

            modelBuilder.Entity("Modelo.Dominio.Precio", b =>
                {
                    b.Property<int>("ComplejoId")
                        .HasColumnType("int");

                    b.Property<int>("CanchaNro")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaDesde")
                        .HasColumnType("date");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioAdicional")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioSena")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ComplejoId", "CanchaNro", "FechaDesde");

                    b.ToTable("Precios");
                });

            modelBuilder.Entity("Modelo.Dominio.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("Modelo.Dominio.TipoCancha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Deporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoCanchas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deporte = "Futbol 11"
                        },
                        new
                        {
                            Id = 2,
                            Deporte = "Futbol 5"
                        },
                        new
                        {
                            Id = 3,
                            Deporte = "Futbol 7"
                        },
                        new
                        {
                            Id = 4,
                            Deporte = "Futsal"
                        },
                        new
                        {
                            Id = 5,
                            Deporte = "Padel"
                        },
                        new
                        {
                            Id = 6,
                            Deporte = "Tenis"
                        },
                        new
                        {
                            Id = 7,
                            Deporte = "Ping Pong"
                        },
                        new
                        {
                            Id = 8,
                            Deporte = "Hockey"
                        },
                        new
                        {
                            Id = 9,
                            Deporte = "Basket"
                        },
                        new
                        {
                            Id = 10,
                            Deporte = "Voley"
                        });
                });

            modelBuilder.Entity("Modelo.Dominio.TipoTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoTurnos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Turno basico",
                            Nombre = "Normal"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Turno reservado periodicamente",
                            Nombre = "Fijo"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Turno reservado para un evento en particular",
                            Nombre = "Evento"
                        });
                });

            modelBuilder.Entity("Modelo.Dominio.TipoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoUsuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Encargado"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Cliente"
                        });
                });

            modelBuilder.Entity("Modelo.Dominio.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CanchaNro")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("ComplejoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<string>("MotivoCancelacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoTurnoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TipoTurnoId");

                    b.HasIndex("ComplejoId", "CanchaNro");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("Modelo.Dominio.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonaFisicaDni")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PersonaJuridicaCuit")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaFisicaDni");

                    b.HasIndex("PersonaJuridicaCuit");

                    b.HasIndex("TipoUsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Modelo.Dominio.Cancha", b =>
                {
                    b.HasOne("Modelo.Dominio.Complejo", "Complejo")
                        .WithMany("Canchas")
                        .HasForeignKey("ComplejoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo.Dominio.TipoCancha", "TipoCancha")
                        .WithMany("Canchas")
                        .HasForeignKey("TipoCanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complejo");

                    b.Navigation("TipoCancha");
                });

            modelBuilder.Entity("Modelo.Dominio.Complejo", b =>
                {
                    b.HasOne("Modelo.Dominio.Usuario", "Dueño")
                        .WithMany("Complejos")
                        .HasForeignKey("DueñoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelo.Dominio.Usuario", "Encargado")
                        .WithOne("Complejo")
                        .HasForeignKey("Modelo.Dominio.Complejo", "EncargadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelo.Dominio.Localidad", "Localidad")
                        .WithMany("Complejos")
                        .HasForeignKey("LocalidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dueño");

                    b.Navigation("Encargado");

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("Modelo.Dominio.Horario", b =>
                {
                    b.HasOne("Modelo.Dominio.Complejo", "Complejo")
                        .WithMany("Horarios")
                        .HasForeignKey("ComplejoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complejo");
                });

            modelBuilder.Entity("Modelo.Dominio.Localidad", b =>
                {
                    b.HasOne("Modelo.Dominio.Provincia", "Provincia")
                        .WithMany("Localidades")
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("Modelo.Dominio.Precio", b =>
                {
                    b.HasOne("Modelo.Dominio.Cancha", "Cancha")
                        .WithMany("Precios")
                        .HasForeignKey("ComplejoId", "CanchaNro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");
                });

            modelBuilder.Entity("Modelo.Dominio.Turno", b =>
                {
                    b.HasOne("Modelo.Dominio.Usuario", "Cliente")
                        .WithMany("Turnos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelo.Dominio.Complejo", "Complejo")
                        .WithMany()
                        .HasForeignKey("ComplejoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo.Dominio.TipoTurno", "TipoTurno")
                        .WithMany("Turnos")
                        .HasForeignKey("TipoTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelo.Dominio.Cancha", "Cancha")
                        .WithMany("Turnos")
                        .HasForeignKey("ComplejoId", "CanchaNro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Cliente");

                    b.Navigation("Complejo");

                    b.Navigation("TipoTurno");
                });

            modelBuilder.Entity("Modelo.Dominio.Usuario", b =>
                {
                    b.HasOne("Modelo.Dominio.PersonaFisica", "PersonaFisica")
                        .WithMany("Usuarios")
                        .HasForeignKey("PersonaFisicaDni");

                    b.HasOne("Modelo.Dominio.PersonaJuridica", "PersonaJuridica")
                        .WithMany("Usuarios")
                        .HasForeignKey("PersonaJuridicaCuit");

                    b.HasOne("Modelo.Dominio.TipoUsuario", "TipoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonaFisica");

                    b.Navigation("PersonaJuridica");

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("Modelo.Dominio.Cancha", b =>
                {
                    b.Navigation("Precios");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Modelo.Dominio.Complejo", b =>
                {
                    b.Navigation("Canchas");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("Modelo.Dominio.Localidad", b =>
                {
                    b.Navigation("Complejos");
                });

            modelBuilder.Entity("Modelo.Dominio.PersonaFisica", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Modelo.Dominio.PersonaJuridica", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Modelo.Dominio.Provincia", b =>
                {
                    b.Navigation("Localidades");
                });

            modelBuilder.Entity("Modelo.Dominio.TipoCancha", b =>
                {
                    b.Navigation("Canchas");
                });

            modelBuilder.Entity("Modelo.Dominio.TipoTurno", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Modelo.Dominio.TipoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Modelo.Dominio.Usuario", b =>
                {
                    b.Navigation("Complejo")
                        .IsRequired();

                    b.Navigation("Complejos");

                    b.Navigation("Turnos");
                });
#pragma warning restore 612, 618
        }
    }
}
